package com.parion.aidat;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.*;
import java.text.*;
import java.util.*;

public class DbHelper extends SQLiteOpenHelper {
    private static final int VERSION=2;
    private final SimpleDateFormat iso=new SimpleDateFormat("yyyy-MM-dd",Locale.US);
    public DbHelper(Context c){super(c,"parion_aidat.db",null,VERSION);iso.setLenient(false);}

    @Override public void onCreate(SQLiteDatabase db){
        db.execSQL("CREATE TABLE athletes(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,birthYear INTEGER DEFAULT 0,birthDate TEXT,tckn TEXT,startDate TEXT,athletePhone TEXT,parent TEXT,phone TEXT,motherName TEXT,motherPhone TEXT,fatherName TEXT,fatherPhone TEXT,school TEXT,classBranch TEXT,groupName TEXT,monthlyFee REAL NOT NULL DEFAULT 0,scholarship INTEGER NOT NULL DEFAULT 0,illnesses TEXT,notes TEXT,leaveDate TEXT,leaveReason TEXT,photoUri TEXT,tshirtQty INTEGER DEFAULT 0,jerseyQty INTEGER DEFAULT 0,tracksuitQty INTEGER DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)");
        db.execSQL("CREATE TABLE payments(id INTEGER PRIMARY KEY AUTOINCREMENT,athleteId INTEGER NOT NULL,year INTEGER NOT NULL,month INTEGER NOT NULL,amount REAL NOT NULL,paymentDate TEXT,method TEXT,note TEXT,UNIQUE(athleteId,year,month),FOREIGN KEY(athleteId) REFERENCES athletes(id) ON DELETE CASCADE)");
        db.execSQL("CREATE TABLE fee_history(id INTEGER PRIMARY KEY AUTOINCREMENT,athleteId INTEGER NOT NULL,effectiveDate TEXT NOT NULL,fee REAL NOT NULL,scholarship INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(athleteId) REFERENCES athletes(id) ON DELETE CASCADE)");
        db.execSQL("CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,isSportsSchool INTEGER NOT NULL DEFAULT 1)");
        db.execSQL("CREATE TABLE group_schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,groupName TEXT NOT NULL,weekday INTEGER NOT NULL,effectiveFrom TEXT NOT NULL)");
        db.execSQL("CREATE TABLE attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,athleteId INTEGER NOT NULL,groupName TEXT NOT NULL,trainingDate TEXT NOT NULL,present INTEGER NOT NULL DEFAULT 1,UNIQUE(athleteId,trainingDate),FOREIGN KEY(athleteId) REFERENCES athletes(id) ON DELETE CASCADE)");
        db.execSQL("CREATE TABLE inventory(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,stock INTEGER NOT NULL DEFAULT 0,buyPrice REAL NOT NULL DEFAULT 0,sellPrice REAL NOT NULL DEFAULT 0)");
        db.execSQL("CREATE TABLE inventory_tx(id INTEGER PRIMARY KEY AUTOINCREMENT,itemId INTEGER NOT NULL,txDate TEXT NOT NULL,qty INTEGER NOT NULL,type TEXT NOT NULL,buyUnit REAL NOT NULL DEFAULT 0,sellUnit REAL NOT NULL DEFAULT 0,athleteId INTEGER,FOREIGN KEY(itemId) REFERENCES inventory(id) ON DELETE CASCADE)");
        seed(db);
    }

    @Override public void onUpgrade(SQLiteDatabase db,int oldVersion,int newVersion){
        if(oldVersion<2){
            String[] alters={
                "ALTER TABLE athletes ADD COLUMN birthDate TEXT","ALTER TABLE athletes ADD COLUMN tckn TEXT","ALTER TABLE athletes ADD COLUMN startDate TEXT","ALTER TABLE athletes ADD COLUMN athletePhone TEXT","ALTER TABLE athletes ADD COLUMN motherName TEXT","ALTER TABLE athletes ADD COLUMN motherPhone TEXT","ALTER TABLE athletes ADD COLUMN fatherName TEXT","ALTER TABLE athletes ADD COLUMN fatherPhone TEXT","ALTER TABLE athletes ADD COLUMN school TEXT","ALTER TABLE athletes ADD COLUMN classBranch TEXT","ALTER TABLE athletes ADD COLUMN scholarship INTEGER NOT NULL DEFAULT 0","ALTER TABLE athletes ADD COLUMN illnesses TEXT","ALTER TABLE athletes ADD COLUMN notes TEXT","ALTER TABLE athletes ADD COLUMN leaveDate TEXT","ALTER TABLE athletes ADD COLUMN leaveReason TEXT","ALTER TABLE athletes ADD COLUMN photoUri TEXT","ALTER TABLE athletes ADD COLUMN tshirtQty INTEGER DEFAULT 0","ALTER TABLE athletes ADD COLUMN jerseyQty INTEGER DEFAULT 0","ALTER TABLE athletes ADD COLUMN tracksuitQty INTEGER DEFAULT 0"};
            for(String s:alters)try{db.execSQL(s);}catch(Exception ignored){}
            db.execSQL("CREATE TABLE IF NOT EXISTS fee_history(id INTEGER PRIMARY KEY AUTOINCREMENT,athleteId INTEGER NOT NULL,effectiveDate TEXT NOT NULL,fee REAL NOT NULL,scholarship INTEGER NOT NULL DEFAULT 0)");
            db.execSQL("CREATE TABLE IF NOT EXISTS groups(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,isSportsSchool INTEGER NOT NULL DEFAULT 1)");
            db.execSQL("CREATE TABLE IF NOT EXISTS group_schedule(id INTEGER PRIMARY KEY AUTOINCREMENT,groupName TEXT NOT NULL,weekday INTEGER NOT NULL,effectiveFrom TEXT NOT NULL)");
            db.execSQL("CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,athleteId INTEGER NOT NULL,groupName TEXT NOT NULL,trainingDate TEXT NOT NULL,present INTEGER NOT NULL DEFAULT 1,UNIQUE(athleteId,trainingDate))");
            db.execSQL("CREATE TABLE IF NOT EXISTS inventory(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,stock INTEGER NOT NULL DEFAULT 0,buyPrice REAL NOT NULL DEFAULT 0,sellPrice REAL NOT NULL DEFAULT 0)");
            db.execSQL("CREATE TABLE IF NOT EXISTS inventory_tx(id INTEGER PRIMARY KEY AUTOINCREMENT,itemId INTEGER NOT NULL,txDate TEXT NOT NULL,qty INTEGER NOT NULL,type TEXT NOT NULL,buyUnit REAL NOT NULL DEFAULT 0,sellUnit REAL NOT NULL DEFAULT 0,athleteId INTEGER)");
            seed(db);
        }
    }
    private void seed(SQLiteDatabase db){
        String[] gs={"Spor Okulu 1","Spor Okulu 2","Spor Okulu 3","Spor Okulu 4"};for(String g:gs)db.execSQL("INSERT OR IGNORE INTO groups(name,isSportsSchool) VALUES(?,1)",new Object[]{g});
        String[] items={"Tişört","Forma","Eşofman"};for(String i:items)db.execSQL("INSERT OR IGNORE INTO inventory(name,stock,buyPrice,sellPrice) VALUES(?,0,0,0)",new Object[]{i});
    }

    public long addAthlete(String name,String birthDate,String tckn,String startDate,String athletePhone,String motherName,String motherPhone,String fatherName,String fatherPhone,String school,String classBranch,String group,double fee,boolean scholarship,String illnesses,String notes,String leaveDate,String leaveReason,String photoUri,int tshirt,int jersey,int tracksuit){
        ContentValues v=new ContentValues();v.put("name",name);v.put("birthDate",birthDate);v.put("tckn",tckn);v.put("startDate",startDate);v.put("athletePhone",athletePhone);v.put("motherName",motherName);v.put("motherPhone",motherPhone);v.put("fatherName",fatherName);v.put("fatherPhone",fatherPhone);v.put("school",school);v.put("classBranch",classBranch);v.put("groupName",group);v.put("monthlyFee",scholarship?0:fee);v.put("scholarship",scholarship?1:0);v.put("illnesses",illnesses);v.put("notes",notes);v.put("leaveDate",leaveDate);v.put("leaveReason",leaveReason);v.put("photoUri",photoUri);v.put("tshirtQty",tshirt);v.put("jerseyQty",jersey);v.put("tracksuitQty",tracksuit);v.put("active",leaveDate==null||leaveDate.trim().isEmpty()?1:0);
        long id=getWritableDatabase().insert("athletes",null,v);if(id>0){ContentValues h=new ContentValues();h.put("athleteId",id);h.put("effectiveDate",validDate(startDate)?startDate:"1900-01-01");h.put("fee",scholarship?0:fee);h.put("scholarship",scholarship?1:0);getWritableDatabase().insert("fee_history",null,h);}return id;
    }
    public Cursor athletes(){return getReadableDatabase().rawQuery("SELECT * FROM athletes ORDER BY active DESC,name COLLATE NOCASE",null);}
    public Cursor activeAthletes(){return getReadableDatabase().rawQuery("SELECT * FROM athletes WHERE active=1 ORDER BY name COLLATE NOCASE",null);}
    public Cursor athletesByGroup(String group){return getReadableDatabase().rawQuery("SELECT * FROM athletes WHERE active=1 AND groupName=? ORDER BY name COLLATE NOCASE",new String[]{group});}
    public Cursor searchAthletes(String q){return getReadableDatabase().rawQuery("SELECT * FROM athletes WHERE name LIKE ? OR tckn LIKE ? ORDER BY active DESC,name COLLATE NOCASE",new String[]{"%"+q+"%","%"+q+"%"});}
    public Cursor athlete(long id){return getReadableDatabase().rawQuery("SELECT * FROM athletes WHERE id=?",new String[]{String.valueOf(id)});}
    public Cursor groups(boolean sportsOnly){return getReadableDatabase().rawQuery("SELECT * FROM groups"+(sportsOnly?" WHERE isSportsSchool=1":"")+" ORDER BY name COLLATE NOCASE",null);}
    public void addGroup(String name,boolean sportsSchool){ContentValues v=new ContentValues();v.put("name",name);v.put("isSportsSchool",sportsSchool?1:0);getWritableDatabase().insertWithOnConflict("groups",null,v,SQLiteDatabase.CONFLICT_IGNORE);}

    public boolean isPaid(long athleteId,int year,int month){Cursor c=getReadableDatabase().rawQuery("SELECT id FROM payments WHERE athleteId=? AND year=? AND month=?",new String[]{String.valueOf(athleteId),String.valueOf(year),String.valueOf(month)});boolean ok=c.moveToFirst();c.close();return ok;}
    public void markPaid(long athleteId,int year,int month,double amount,String method){ContentValues v=new ContentValues();v.put("athleteId",athleteId);v.put("year",year);v.put("month",month);v.put("amount",amount);v.put("paymentDate",iso.format(new Date()));v.put("method",method);getWritableDatabase().insertWithOnConflict("payments",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public void removePayment(long athleteId,int year,int month){getWritableDatabase().delete("payments","athleteId=? AND year=? AND month=?",new String[]{String.valueOf(athleteId),String.valueOf(year),String.valueOf(month)});}
    public double collected(int year,int month){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(amount),0) FROM payments WHERE year=? AND month=?",new String[]{String.valueOf(year),String.valueOf(month)});c.moveToFirst();double x=c.getDouble(0);c.close();return x;}
    public Cursor paymentsFor(long athleteId){return getReadableDatabase().rawQuery("SELECT * FROM payments WHERE athleteId=? ORDER BY year DESC,month DESC",new String[]{String.valueOf(athleteId)});}

    private Date parse(String s){try{return iso.parse(s);}catch(Exception e){return null;}}
    private boolean validDate(String s){return parse(s)!=null;}
    public String dueDate(long athleteId,int year,int month){Cursor c=athlete(athleteId);if(!c.moveToFirst()){c.close();return null;}String st=c.getString(c.getColumnIndexOrThrow("startDate"));c.close();Date d=parse(st);if(d==null)return String.format(Locale.US,"%04d-%02d-01",year,month);Calendar first=Calendar.getInstance();first.setTime(d);first.add(Calendar.MONTH,1);Calendar target=Calendar.getInstance();target.clear();target.set(year,month-1,1);if(target.before(monthStart(first)))return null;int day=first.get(Calendar.DAY_OF_MONTH);int max=target.getActualMaximum(Calendar.DAY_OF_MONTH);target.set(Calendar.DAY_OF_MONTH,Math.min(day,max));return iso.format(target.getTime());}
    private Calendar monthStart(Calendar in){Calendar c=(Calendar)in.clone();c.set(Calendar.DAY_OF_MONTH,1);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c;}
    public double feeForDate(long athleteId,String date){Cursor c=getReadableDatabase().rawQuery("SELECT fee,scholarship FROM fee_history WHERE athleteId=? AND effectiveDate<=? ORDER BY effectiveDate DESC,id DESC LIMIT 1",new String[]{String.valueOf(athleteId),date});if(c.moveToFirst()){double f=c.getInt(1)==1?0:c.getDouble(0);c.close();return f;}c.close();Cursor a=athlete(athleteId);double f=0;if(a.moveToFirst())f=a.getInt(a.getColumnIndexOrThrow("scholarship"))==1?0:a.getDouble(a.getColumnIndexOrThrow("monthlyFee"));a.close();return f;}
    public double expectedForMonth(long athleteId,int year,int month){String due=dueDate(athleteId,year,month);return due==null?0:feeForDate(athleteId,due);}
    public double expectedTotal(int year,int month){double t=0;Cursor c=activeAthletes();while(c.moveToNext())t+=expectedForMonth(c.getLong(c.getColumnIndexOrThrow("id")),year,month);c.close();return t;}
    public int unpaidCount(int year,int month){int n=0;Cursor c=activeAthletes();while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));if(expectedForMonth(id,year,month)>0&&!isPaid(id,year,month))n++;}c.close();return n;}
    private void ensureBaseline(long id,double oldFee,int oldScholarship){Cursor c=getReadableDatabase().rawQuery("SELECT id FROM fee_history WHERE athleteId=? LIMIT 1",new String[]{String.valueOf(id)});boolean has=c.moveToFirst();c.close();if(!has){ContentValues h=new ContentValues();h.put("athleteId",id);h.put("effectiveDate","1900-01-01");h.put("fee",oldFee);h.put("scholarship",oldScholarship);getWritableDatabase().insert("fee_history",null,h);}}
    public void updateFee(long id,double newFee,boolean scholarship,String effectiveDate){Cursor a=athlete(id);if(!a.moveToFirst()){a.close();return;}double old=a.getDouble(a.getColumnIndexOrThrow("monthlyFee"));int oldS=a.getInt(a.getColumnIndexOrThrow("scholarship"));a.close();ensureBaseline(id,old,oldS);ContentValues h=new ContentValues();h.put("athleteId",id);h.put("effectiveDate",effectiveDate);h.put("fee",scholarship?0:newFee);h.put("scholarship",scholarship?1:0);getWritableDatabase().insert("fee_history",null,h);ContentValues v=new ContentValues();v.put("monthlyFee",scholarship?0:newFee);v.put("scholarship",scholarship?1:0);getWritableDatabase().update("athletes",v,"id=?",new String[]{String.valueOf(id)});}
    public int bulkUpdateFee(String group,double oldFee,double newFee,String effectiveDate){Cursor c=getReadableDatabase().rawQuery("SELECT id FROM athletes WHERE active=1 AND groupName=? AND ABS(monthlyFee-?)<0.01 AND scholarship=0",new String[]{group,String.valueOf(oldFee)});ArrayList<Long> ids=new ArrayList<>();while(c.moveToNext())ids.add(c.getLong(0));c.close();for(long id:ids)updateFee(id,newFee,false,effectiveDate);return ids.size();}
    public void updateEquipment(long id,int tshirt,int jersey,int tracksuit){ContentValues v=new ContentValues();v.put("tshirtQty",tshirt);v.put("jerseyQty",jersey);v.put("tracksuitQty",tracksuit);getWritableDatabase().update("athletes",v,"id=?",new String[]{String.valueOf(id)});}

    public int[] scheduleDays(String group){Cursor c=getReadableDatabase().rawQuery("SELECT weekday FROM group_schedule WHERE groupName=? ORDER BY weekday",new String[]{group});ArrayList<Integer> a=new ArrayList<>();while(c.moveToNext())a.add(c.getInt(0));c.close();int[] x=new int[a.size()];for(int i=0;i<a.size();i++)x[i]=a.get(i);return x;}
    public void setSchedule(String group,boolean[] selected){SQLiteDatabase d=getWritableDatabase();d.delete("group_schedule","groupName=?",new String[]{group});String today=iso.format(new Date());for(int i=0;i<selected.length;i++)if(selected[i]){ContentValues v=new ContentValues();v.put("groupName",group);v.put("weekday",i+2>7?1:i+2);v.put("effectiveFrom",today);d.insert("group_schedule",null,v);}}
    public ArrayList<String> trainingDates(String group,int year,int month){int[] days=scheduleDays(group);HashSet<Integer> set=new HashSet<>();for(int d:days)set.add(d);ArrayList<String> out=new ArrayList<>();Calendar c=Calendar.getInstance();c.clear();c.set(year,month-1,1);int max=c.getActualMaximum(Calendar.DAY_OF_MONTH);for(int day=1;day<=max;day++){c.set(Calendar.DAY_OF_MONTH,day);if(set.contains(c.get(Calendar.DAY_OF_WEEK)))out.add(iso.format(c.getTime()));}return out;}
    public void saveAttendance(long athleteId,String group,String date,boolean present){ContentValues v=new ContentValues();v.put("athleteId",athleteId);v.put("groupName",group);v.put("trainingDate",date);v.put("present",present?1:0);getWritableDatabase().insertWithOnConflict("attendance",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public boolean attendanceValue(long athleteId,String date){Cursor c=getReadableDatabase().rawQuery("SELECT present FROM attendance WHERE athleteId=? AND trainingDate=?",new String[]{String.valueOf(athleteId),date});boolean p=!c.moveToFirst()||c.getInt(0)==1;c.close();return p;}
    public Cursor absentOver10Days(){return getReadableDatabase().rawQuery("SELECT a.*,MAX(CASE WHEN at.present=1 THEN at.trainingDate ELSE NULL END) lastPresent,MAX(at.trainingDate) lastAttendance FROM athletes a JOIN groups g ON g.name=a.groupName AND g.isSportsSchool=1 JOIN attendance at ON at.athleteId=a.id WHERE a.active=1 GROUP BY a.id HAVING lastAttendance IS NOT NULL AND (lastPresent IS NULL OR julianday('now')-julianday(lastPresent)>=10) ORDER BY a.name",null);}

    public Cursor inventory(){return getReadableDatabase().rawQuery("SELECT * FROM inventory ORDER BY name",null);}
    public void addInventoryItem(String name,int stock,double buy,double sell){ContentValues v=new ContentValues();v.put("name",name);v.put("stock",stock);v.put("buyPrice",buy);v.put("sellPrice",sell);getWritableDatabase().insertWithOnConflict("inventory",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    public void inventoryTx(long itemId,int qty,String type,double buy,double sell,Long athleteId){ContentValues tx=new ContentValues();tx.put("itemId",itemId);tx.put("txDate",iso.format(new Date()));tx.put("qty",qty);tx.put("type",type);tx.put("buyUnit",buy);tx.put("sellUnit",sell);if(athleteId!=null)tx.put("athleteId",athleteId);getWritableDatabase().insert("inventory_tx",null,tx);getWritableDatabase().execSQL("UPDATE inventory SET stock=stock+? WHERE id=?",new Object[]{type.equals("IN")?qty:-qty,itemId});}
    public double inventoryProfit(String from,String to){Cursor c=getReadableDatabase().rawQuery("SELECT COALESCE(SUM(qty*(sellUnit-buyUnit)),0) FROM inventory_tx WHERE type='OUT' AND txDate BETWEEN ? AND ?",new String[]{from,to});c.moveToFirst();double x=c.getDouble(0);c.close();return x;}
}
