package com.parion.aidat;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.view.*;
import android.widget.*;
import java.text.Collator;
import java.util.*;

public class MainActivityV37 extends MainActivityV36 {
    final String[] SORTS={"AD (A-Z)","AD (Z-A)","SOYAD (A-Z)","SOYAD (Z-A)","DOĞUM TARİHİ/YILI ↑","DOĞUM TARİHİ/YILI ↓","GRUP / TAKIM (A-Z)","GRUP / TAKIM (Z-A)","AİDAT ₺ ↑","AİDAT ₺ ↓"};
    static class A{long id;String name,cat,status,notes,photo,birthDate;int by,fee;}

    @Override public void onCreate(android.os.Bundle b){super.onCreate(b);ensureBirthDate();}
    void ensureBirthDate(){try{Cursor c=db.getReadableDatabase().rawQuery("PRAGMA table_info(athletes)",null);boolean ok=false;while(c.moveToNext())if("birthDate".equals(c.getString(c.getColumnIndexOrThrow("name"))))ok=true;c.close();if(!ok)db.getWritableDatabase().execSQL("ALTER TABLE athletes ADD COLUMN birthDate TEXT");}catch(Exception ignored){}}

    A a(Cursor c){A x=new A();x.id=c.getLong(c.getColumnIndexOrThrow("id"));x.name=s(c,"name");x.cat=s(c,"category");x.status=s(c,"status");x.notes=s(c,"notes");x.photo=s(c,"photo");x.by=c.getInt(c.getColumnIndexOrThrow("birthYear"));x.fee=c.getInt(c.getColumnIndexOrThrow("monthlyFee"));int i=c.getColumnIndex("birthDate");x.birthDate=i>=0&&!c.isNull(i)?c.getString(i):"";return x;}
    String surname(String n){String[] p=(n==null?"":n.trim()).split("\\s+");return p.length==0?"":p[p.length-1];}
    String birthKey(A x){return x.birthDate!=null&&x.birthDate.matches("\\d{4}-\\d{2}-\\d{2}")?x.birthDate:String.format(Locale.US,"%04d-01-01",x.by);}
    Comparator<A> cmp(int m){Collator tr=Collator.getInstance(new Locale("tr","TR"));tr.setStrength(Collator.PRIMARY);return (x,y)->{int r;switch(m){case 1:return -tr.compare(x.name,y.name);case 2:return tr.compare(surname(x.name),surname(y.name));case 3:return -tr.compare(surname(x.name),surname(y.name));case 4:return birthKey(x).compareTo(birthKey(y));case 5:return birthKey(y).compareTo(birthKey(x));case 6:return tr.compare(x.cat,y.cat);case 7:return -tr.compare(x.cat,y.cat);case 8:return Integer.compare(x.fee,y.fee);case 9:return Integer.compare(y.fee,x.fee);default:return tr.compare(x.name,y.name);}};}

    @Override void showAthletes(){
        page="LIST";base("SPORCULAR",true);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(8),dp(8),dp(8),dp(6));p.setBackground(round(Color.WHITE,10));
        Button add=btn("+ YENİ KAYIT");add.setOnClickListener(v->form(-1));p.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));
        EditText q=new EditText(this);q.setHint("Sporcu adı ara");p.addView(q,new LinearLayout.LayoutParams(-1,dp(48)));
        LinearLayout r1=new LinearLayout(this);Spinner st=sp(new String[]{"TÜM DURUMLAR","AKTİF","ARA VERDİ","BIRAKTI","ARANACAK","SAKATLANDI"},"");Spinner cat=sp(new String[]{"TÜM KATEGORİLER","SO 1","SO 2","SO 3","MİNİ VOLEYBOL","MİDİ","KÜÇÜK","YILDIZ","GENÇ"},"");r1.addView(st,new LinearLayout.LayoutParams(0,dp(48),1));r1.addView(cat,new LinearLayout.LayoutParams(0,dp(48),1));p.addView(r1);
        LinearLayout r2=new LinearLayout(this);EditText by=new EditText(this);by.setHint("Doğum yılı");by.setInputType(2);Spinner sort=sp(SORTS,"");r2.addView(by,new LinearLayout.LayoutParams(0,dp(48),1));r2.addView(sort,new LinearLayout.LayoutParams(0,dp(48),1));p.addView(r2);
        ArrayList<String> ni=new ArrayList<>();ni.add("TÜM ÖZEL NOTLAR");ni.addAll(db.uniqueNotes());Spinner note=new Spinner(this);note.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ni));p.addView(note,new LinearLayout.LayoutParams(-1,dp(52)));root.addView(p);
        ScrollView sv=scroll();LinearLayout list=box(sv);Runnable load=()->load(list,q.getText().toString(),String.valueOf(st.getSelectedItem()),String.valueOf(cat.getSelectedItem()),by.getText().toString(),String.valueOf(note.getSelectedItem()),sort.getSelectedItemPosition());
        android.text.TextWatcher tw=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){load.run();}public void afterTextChanged(android.text.Editable e){}};q.addTextChangedListener(tw);by.addTextChangedListener(tw);android.widget.AdapterView.OnItemSelectedListener sl=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){load.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}};st.setOnItemSelectedListener(sl);cat.setOnItemSelectedListener(sl);note.setOnItemSelectedListener(sl);sort.setOnItemSelectedListener(sl);load.run();
    }
    void load(LinearLayout b,String q,String stat,String cat,String by,String note,int sort){b.removeAllViews();Cursor c=db.athletes(q,stat.startsWith("TÜM")?"TÜMÜ":stat);ArrayList<A> xs=new ArrayList<>();int y=0;try{y=Integer.parseInt(by.trim());}catch(Exception ignored){}while(c.moveToNext()){A x=a(c);if(!cat.startsWith("TÜM")&&!cat.equalsIgnoreCase(x.cat))continue;if(y>0&&x.by!=y)continue;if(!note.startsWith("TÜM")&&!note.trim().equals(x.notes==null?"":x.notes.trim()))continue;xs.add(x);}c.close();Collections.sort(xs,cmp(sort));for(A x:xs)row(b,x,null,0);if(xs.isEmpty())b.addView(tv("FİLTRELERE UYGUN SPORCU BULUNAMADI",14,Color.DKGRAY,true));}
    void row(LinearLayout b,A x,String detail,int amount){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(8),dp(7),dp(8),dp(7));r.setBackground(round(Color.WHITE,10));ImageView av=new ImageView(this);av.setScaleType(ImageView.ScaleType.CENTER_CROP);setAthletePhoto(av,x.photo);r.addView(av,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv((x.by>0?x.by+" • ":"")+x.name,15,BLACK,true));t.addView(tv(x.cat+(x.status==null||x.status.isEmpty()?"":" • "+x.status)+" • "+money(x.fee),12,Color.DKGRAY,false));if(detail!=null)t.addView(tv(detail,12,Color.DKGRAY,false));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));if(amount>0)r.addView(tv(money(amount),14,BLACK,true),new LinearLayout.LayoutParams(dp(115),-2));final long id=x.id;r.setOnClickListener(v->showProfile(id));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(7));b.addView(r,lp);}

    @Override void showDashList(String title,LinkedHashMap<Long,DashItem> map){page="LIST";base(title,true);Spinner sort=sp(SORTS,"");root.addView(sort,new LinearLayout.LayoutParams(-1,dp(52)));ScrollView sv=scroll();LinearLayout b=box(sv);Runnable load=()->{b.removeAllViews();ArrayList<A> xs=new ArrayList<>();HashMap<Long,DashItem> dm=new HashMap<>();for(DashItem d:map.values()){Cursor c=db.athlete(d.id);if(c.moveToFirst()){A x=a(c);xs.add(x);dm.put(x.id,d);}c.close();}Collections.sort(xs,cmp(sort.getSelectedItemPosition()));for(A x:xs){DashItem d=dm.get(x.id);row(b,x,d==null?null:d.detail,d==null?0:d.amount);}if(xs.isEmpty())b.addView(tv("Bu grupta sporcu bulunmuyor.",15,Color.DKGRAY,true));};sort.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){load.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});load.run();}

    @Override void showProfile(long id){super.showProfile(id);LinearLayout b=findBox(root);if(b==null)return;LinearLayout r=new LinearLayout(this);Button e=btn("BİLGİLERİ DÜZENLE"),d=btn("SPORCUYU SİL");e.setOnClickListener(v->form(id));d.setBackground(round(Color.rgb(245,210,210),12));d.setOnClickListener(v->confirmDelete(id));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(56),1);lp.setMargins(dp(2),dp(8),dp(2),0);r.addView(e,lp);r.addView(d,lp);b.addView(r);}
    LinearLayout findBox(View v){if(v instanceof ScrollView){ScrollView s=(ScrollView)v;if(s.getChildCount()>0&&s.getChildAt(0) instanceof LinearLayout)return (LinearLayout)s.getChildAt(0);}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){LinearLayout x=findBox(g.getChildAt(i));if(x!=null)return x;}}return null;}

    void form(long id){page="FORM";base(id<0?"YENİ SPORCU KAYDI":"SPORCU BİLGİLERİNİ DÜZENLE",true);ScrollView sv=scroll();LinearLayout b=box(sv);Cursor c=id<0?null:db.athlete(id);if(c!=null)c.moveToFirst();EditText name=f("AD SOYAD",v(c,"name")),bd=f("DOĞUM TARİHİ (gg.aa.yyyy)",birth(c)),cat=f("GRUP / TAKIM",v(c,"category")),fee=f("AYLIK AİDAT ₺",n(c,"monthlyFee")),phone=f("SPORCU TELEFON",v(c,"phone")),mn=f("ANNE ADI",v(c,"motherName")),mp=f("ANNE TELEFON",v(c,"motherPhone")),fn=f("BABA ADI",v(c,"fatherName")),fp=f("BABA TELEFON",v(c,"fatherPhone")),start=f("BAŞLANGIÇ TARİHİ",dt(c,"startDate")),end=f("BİTİŞ / ARA VERME",dt(c,"endDate")),restart=f("YENİDEN BAŞLAMA",dt(c,"restartDate")),notes=f("ÖZEL NOTLAR",v(c,"notes"));fee.setInputType(2);notes.setMinLines(3);Spinner status=sp(new String[]{"AKTİF","ARA VERDİ","BIRAKTI","ARANACAK","SAKATLANDI"},v(c,"status"));Spinner sibling=sp(new String[]{"TEK","VAR","BURSLU"},v(c,"sibling"));if(c!=null)c.close();View[] vs={name,bd,cat,status,fee,sibling,phone,mn,mp,fn,fp,start,end,restart,notes};for(View z:vs)b.addView(z);Button save=btn(id<0?"KAYDI OLUŞTUR":"DEĞİŞİKLİKLERİ KAYDET");b.addView(save,new LinearLayout.LayoutParams(-1,dp(60)));save.setOnClickListener(vv->{if(name.getText().toString().trim().isEmpty()){Toast.makeText(this,"Ad Soyad zorunludur.",Toast.LENGTH_SHORT).show();return;}ContentValues cv=new ContentValues();String bi=iso(bd.getText().toString());cv.put("name",name.getText().toString().trim().toUpperCase(new Locale("tr","TR")));cv.put("birthDate",bi);cv.put("birthYear",bi.length()>=4?parseInt(bi.substring(0,4)):0);cv.put("category",cat.getText().toString().trim().toUpperCase(new Locale("tr","TR")));cv.put("status",String.valueOf(status.getSelectedItem()));cv.put("monthlyFee",parseInt(fee.getText().toString()));cv.put("sibling",String.valueOf(sibling.getSelectedItem()));cv.put("phone",phone.getText().toString().trim());cv.put("motherName",mn.getText().toString().trim());cv.put("motherPhone",mp.getText().toString().trim());cv.put("fatherName",fn.getText().toString().trim());cv.put("fatherPhone",fp.getText().toString().trim());cv.put("startDate",iso(start.getText().toString()));cv.put("endDate",iso(end.getText().toString()));cv.put("restartDate",iso(restart.getText().toString()));cv.put("notes",notes.getText().toString().trim());SQLiteDatabase d=db.getWritableDatabase();long saved=id;if(id<0){Cursor m=d.rawQuery("SELECT COALESCE(MAX(seq),0)+1 FROM athletes",null);m.moveToFirst();cv.put("seq",m.getInt(0));m.close();cv.put("photo","");saved=d.insert("athletes",null,cv);}else d.update("athletes",cv,"id=?",new String[]{String.valueOf(id)});if(saved>0){Toast.makeText(this,"Kayıt kaydedildi.",Toast.LENGTH_SHORT).show();showProfile(saved);}});}
    EditText f(String h,String x){EditText e=new EditText(this);e.setHint(h);e.setText(x==null?"":x);return e;}Spinner sp(String[] a,String s){Spinner x=new Spinner(this);x.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,a));for(int i=0;i<a.length;i++)if(a[i].equalsIgnoreCase(s)){x.setSelection(i);break;}return x;}String v(Cursor c,String col){if(c==null)return "";int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":c.getString(i);}String n(Cursor c,String col){if(c==null)return "";int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":String.valueOf(c.getInt(i));}String dt(Cursor c,String col){String x=v(c,col);return x.isEmpty()?"":dateTr(x);}String birth(Cursor c){String x=v(c,"birthDate");if(!x.isEmpty())return dateTr(x);int y=0;if(c!=null){int i=c.getColumnIndex("birthYear");if(i>=0)y=c.getInt(i);}return y>0?"01.01."+y:"";}String iso(String x){x=x==null?"":x.trim();if(x.isEmpty())return "";String z=toIso(x);return z==null?"":z;}
    void confirmDelete(long id){Cursor c=db.athlete(id);String name="SPORCU";if(c.moveToFirst())name=s(c,"name");c.close();String n=name;new AlertDialog.Builder(this).setTitle("SPORCUYU SİL").setMessage(n+" ve tüm aidat geçmişi silinsin mi?").setPositiveButton("DEVAM",(d,w)->new AlertDialog.Builder(this).setTitle("SON ONAY").setMessage("Bu işlem geri alınamaz.").setPositiveButton("EVET, SİL",(a,z)->del(id)).setNegativeButton("VAZGEÇ",null).show()).setNegativeButton("İPTAL",null).show();}
    void del(long id){SQLiteDatabase d=db.getWritableDatabase();d.beginTransaction();try{d.delete("payments","athleteId=?",new String[]{String.valueOf(id)});d.delete("fee_history","athleteId=?",new String[]{String.valueOf(id)});d.delete("athletes","id=?",new String[]{String.valueOf(id)});d.setTransactionSuccessful();}finally{d.endTransaction();}Toast.makeText(this,"Sporcu silindi.",Toast.LENGTH_SHORT).show();showAthletes();}
}
