package com.parion.aidat;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.MediaStore;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    static final int GOLD=Color.rgb(212,175,55), BLACK=Color.rgb(17,17,17), BG=Color.rgb(246,246,246);
    static final int GREEN=Color.rgb(26,145,70), YELLOW=Color.rgb(255,215,64), RED=Color.rgb(220,53,69), ORANGE=Color.rgb(245,158,11), GRAY=Color.rgb(180,180,180);
    DbHelper db; LinearLayout root; long currentAthlete=-1; String page="HOME"; final Locale TR=new Locale("tr","TR");

    @Override public void onCreate(Bundle b){super.onCreate(b);db=new DbHelper(this);showHome();}
    TextView tv(String text,int sp,int color,boolean bold){TextView v=new TextView(this);v.setText(text);v.setTextSize(sp);v.setTextColor(color);v.setPadding(dp(10),dp(8),dp(10),dp(8));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}
    Button btn(String text){Button b=new Button(this);b.setText(text);b.setTextSize(14);b.setTextColor(BLACK);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(round(GOLD,12));b.setPadding(dp(8),dp(8),dp(8),dp(8));return b;}
    GradientDrawable round(int color,int r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
    int dp(int x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    void base(String title,boolean back){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(10),dp(8),dp(10),dp(8));bar.setBackgroundColor(BLACK);if(back){TextView b=tv("‹",36,Color.WHITE,true);b.setOnClickListener(v->goBack());bar.addView(b,new LinearLayout.LayoutParams(dp(52),dp(52)));}TextView t=tv(title,19,GOLD,true);bar.addView(t,new LinearLayout.LayoutParams(0,dp(56),1));root.addView(bar);}
    ScrollView scroll(){ScrollView s=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),dp(12),dp(12),dp(28));s.addView(box);s.setTag(box);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));return s;}
    LinearLayout box(ScrollView s){return (LinearLayout)s.getTag();}

    void showHome(){page="HOME";currentAthlete=-1;base("PARION SPOR OKULU",false);ScrollView s=scroll();LinearLayout b=box(s);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.parion_logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);b.addView(logo,new LinearLayout.LayoutParams(-1,dp(120)));Calendar c=Calendar.getInstance();int paid=db.paidThisMonth(c.get(Calendar.YEAR),c.get(Calendar.MONTH)+1);LinearLayout cards=new LinearLayout(this);cards.setOrientation(LinearLayout.HORIZONTAL);cards.addView(card("AKTİF",String.valueOf(db.count("AKTİF")),GREEN),new LinearLayout.LayoutParams(0,dp(100),1));cards.addView(card("ARA VERDİ",String.valueOf(db.count("ARA VERDİ")),ORANGE),new LinearLayout.LayoutParams(0,dp(100),1));cards.addView(card("BU AY",money(paid),GOLD),new LinearLayout.LayoutParams(0,dp(100),1));b.addView(cards);Button athletes=btn("SPORCULAR");athletes.setOnClickListener(v->showAthletes());b.addView(athletes,new LinearLayout.LayoutParams(-1,dp(58)));TextView info=tv("2026 Excel verileri uygulamanın başlangıç veritabanına gömülüdür. Aidat renkleri: yeşil ödendi, sarı ödeme dönemi, kırmızı gecikmiş, gri ara verdi, turuncu eksik/fazla ödeme.",13,Color.DKGRAY,false);b.addView(info);}
    View card(String a,String n,int color){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setGravity(Gravity.CENTER);x.setPadding(dp(4),dp(8),dp(4),dp(8));x.setBackground(round(Color.WHITE,12));TextView v=tv(n,20,color,true);v.setGravity(Gravity.CENTER);TextView l=tv(a,11,Color.DKGRAY,true);l.setGravity(Gravity.CENTER);x.addView(v);x.addView(l);return x;}

    void showAthletes(){page="LIST";base("SPORCULAR",true);LinearLayout filters=new LinearLayout(this);filters.setPadding(dp(8),dp(8),dp(8),dp(4));EditText q=new EditText(this);q.setHint("Sporcu ara");Spinner st=new Spinner(this);String[] sts={"TÜMÜ","AKTİF","ARA VERDİ","BIRAKTI"};st.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,sts));filters.addView(q,new LinearLayout.LayoutParams(0,dp(55),2));filters.addView(st,new LinearLayout.LayoutParams(0,dp(55),1));root.addView(filters);ScrollView s=scroll();LinearLayout b=box(s);Runnable load=()->loadAthletes(b,q.getText().toString(),String.valueOf(st.getSelectedItem()));q.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int x,int y){}public void onTextChanged(CharSequence s,int a,int b,int c){load.run();}public void afterTextChanged(android.text.Editable e){}});st.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){load.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});load.run();}
    void loadAthletes(LinearLayout b,String q,String status){b.removeAllViews();Cursor c=db.athletes(q,status);while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String name=s(c,"name"),cat=s(c,"category"),stat=s(c,"status");int by=c.getInt(c.getColumnIndexOrThrow("birthYear"));LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(7),dp(8),dp(7));ImageView av=new ImageView(this);av.setImageResource(R.drawable.parion_logo);av.setScaleType(ImageView.ScaleType.CENTER_CROP);row.addView(av,new LinearLayout.LayoutParams(dp(56),dp(56)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv((by>0?by+" • ":"")+name,15,BLACK,true));t.addView(tv(cat+" • "+stat,12,statusColor(stat),false));row.addView(t,new LinearLayout.LayoutParams(0,-2,1));row.setBackground(round(Color.WHITE,10));row.setOnClickListener(v->showProfile(id));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(7));b.addView(row,lp);}c.close();}

    void showProfile(long id){page="PROFILE";currentAthlete=id;Cursor c=db.athlete(id);if(!c.moveToFirst()){c.close();showAthletes();return;}String name=s(c,"name");base(name,true);ScrollView sv=scroll();LinearLayout b=box(sv);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);ImageView av=new ImageView(this);av.setImageResource(R.drawable.parion_logo);av.setScaleType(ImageView.ScaleType.CENTER_CROP);head.addView(av,new LinearLayout.LayoutParams(dp(92),dp(92)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.addView(tv(s(c,"category")+" • "+s(c,"status"),15,statusColor(s(c,"status")),true));info.addView(tv("Doğum yılı: "+c.getInt(c.getColumnIndexOrThrow("birthYear")),13,Color.DKGRAY,false));info.addView(tv("Aylık aidat: "+money(c.getInt(c.getColumnIndexOrThrow("monthlyFee"))),14,BLACK,true));head.addView(info,new LinearLayout.LayoutParams(0,-2,1));b.addView(head);b.addView(line("Sporcu Tel",s(c,"phone")));b.addView(line("Anne",join(s(c,"motherName"),s(c,"motherPhone"))));b.addView(line("Baba",join(s(c,"fatherName"),s(c,"fatherPhone"))));b.addView(line("Kardeş",s(c,"sibling")));b.addView(line("İlk Kayıt",dateTr(s(c,"startDate"))));b.addView(line("Bitiş / Ara Verme",dateTr(s(c,"endDate"))));b.addView(line("Yeniden Başlama",dateTr(s(c,"restartDate"))));if(!s(c,"notes").isEmpty())b.addView(line("Özel Not",s(c,"notes")));int fee=c.getInt(c.getColumnIndexOrThrow("monthlyFee"));String status=s(c,"status"),start=s(c,"startDate"),end=s(c,"endDate"),restart=s(c,"restartDate"),sib=s(c,"sibling");c.close();TextView h=tv("2026 AİDAT HAREKETLERİ",16,BLACK,true);h.setPadding(dp(10),dp(20),dp(10),dp(8));b.addView(h);HashMap<Integer,String[]> pays=new HashMap<>();Cursor p=db.payments(id);while(p.moveToNext())pays.put(p.getInt(p.getColumnIndexOrThrow("month")),new String[]{s(p,"marker"),String.valueOf(p.getInt(p.getColumnIndexOrThrow("amount")))});p.close();for(int m=1;m<=12;m++){String[] a=pays.get(m);String marker=a==null?"":a[0];int amount=a==null?0:Integer.parseInt(a[1]);View row=paymentRow(id,m,fee,sib,status,start,end,restart,marker,amount);b.addView(row);}Button report=btn("YILLIK AİDAT RAPORUNU PAYLAŞ");report.setOnClickListener(v->shareReport(id));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(58));rp.setMargins(0,dp(16),0,dp(8));b.addView(report,rp);}
    View line(String label,String value){LinearLayout r=new LinearLayout(this);r.setPadding(dp(4),dp(2),dp(4),dp(2));TextView l=tv(label,12,Color.GRAY,true);TextView v=tv(value==null||value.isEmpty()?"—":value,13,BLACK,false);r.addView(l,new LinearLayout.LayoutParams(dp(135),-2));r.addView(v,new LinearLayout.LayoutParams(0,-2,1));return r;}
    View paymentRow(long id,int m,int fee,String sibling,String status,String start,String end,String restart,String marker,int amount){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(8),dp(7),dp(8),dp(7));int color=paymentColor(m,fee,sibling,start,end,restart,marker,amount);r.setBackground(round(color,9));TextView month=tv(monthName(m),13,Color.BLACK,true);TextView detail=tv(paymentText(m,fee,sibling,start,end,restart,marker,amount),12,Color.BLACK,false);r.addView(month,new LinearLayout.LayoutParams(dp(88),-2));r.addView(detail,new LinearLayout.LayoutParams(0,-2,1));r.setOnClickListener(v->editPayment(id,m,fee,marker,amount));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(5));r.setLayoutParams(lp);return r;}
    int paymentColor(int m,int fee,String sibling,String start,String end,String restart,String marker,int amount){if("X".equals(marker))return GRAY;if("!".equals(marker)||"!!".equals(marker)||amount>0&&fee>0&&amount!=fee)return ORANGE;if(isDate(marker))return GREEN;if("BURSLU".equals(sibling)||fee==0)return Color.rgb(225,225,225);if(!activeMonth(m,start,end,restart))return Color.rgb(230,230,230);Calendar now=Calendar.getInstance();int y=now.get(Calendar.YEAR),cm=now.get(Calendar.MONTH)+1;if(y<2026||m>cm)return Color.WHITE;if(y==2026&&m==cm)return YELLOW;return RED;}
    String paymentText(int m,int fee,String sibling,String start,String end,String restart,String marker,int amount){if("X".equals(marker))return "ARA VERDİ";if("!".equals(marker)||"!!".equals(marker))return money(amount)+" • "+(amount<fee?"EKSİK ÖDEME":amount>fee?"FAZLA ÖDEME":"ÖDENDİ");if(isDate(marker))return dateTr(marker)+" • "+money(amount)+(fee>0&&amount!=fee?amount<fee?" • EKSİK":" • FAZLA":" • ÖDENDİ");if("BURSLU".equals(sibling)||fee==0)return "BURSLU";if(!activeMonth(m,start,end,restart))return "AKTİF DEĞİL";Calendar now=Calendar.getInstance();if(now.get(Calendar.YEAR)>2026||now.get(Calendar.YEAR)==2026&&m<now.get(Calendar.MONTH)+1)return "ÖDEME GECİKTİ";if(now.get(Calendar.YEAR)==2026&&m==now.get(Calendar.MONTH)+1)return "ÖDEME DÖNEMİ";return "BEKLİYOR";}
    boolean activeMonth(int m,String start,String end,String restart){String first=String.format(Locale.US,"2026-%02d-01",m),last=String.format(Locale.US,"2026-%02d-31",m);if(!start.isEmpty()&&start.compareTo(last)>0)return false;if(end.isEmpty()||"DEVAM".equalsIgnoreCase(end))return true;if(end.compareTo(first)>=0)return true;return !restart.isEmpty()&&restart.compareTo(last)<=0;}
    void editPayment(long id,int month,int fee,String marker,int amount){final String[] opts={"ÖDEME GİR","ARA VERDİ (X)","FARKLI TUTAR (!)","KAYDI TEMİZLE"};new AlertDialog.Builder(this).setTitle(monthName(month)+" 2026").setItems(opts,(d,w)->{if(w==1){db.updatePayment(id,month,"X",0);showProfile(id);}else if(w==3){db.updatePayment(id,month,"",0);showProfile(id);}else{LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(dp(20),0,dp(20),0);EditText date=new EditText(this);date.setHint("Ödeme tarihi (gg.aa.yyyy)");date.setText(isDate(marker)?dateTr(marker):new SimpleDateFormat("dd.MM.yyyy",TR).format(new Date()));EditText am=new EditText(this);am.setHint("Tutar");am.setInputType(2);am.setText(String.valueOf(amount>0?amount:fee));x.addView(date);x.addView(am);new AlertDialog.Builder(this).setTitle(w==2?"Farklı tutar":"Aidat ödemesi").setView(x).setPositiveButton("KAYDET",(a,z)->{String iso=toIso(date.getText().toString());int val=parseInt(am.getText().toString());db.updatePayment(id,month,w==2?"!":iso,val);showProfile(id);}).setNegativeButton("İPTAL",null).show();}}).show();}

    void shareReport(long id){Cursor a=db.athlete(id);if(!a.moveToFirst()){a.close();return;}String name=s(a,"name"),category=s(a,"category"),sibling=s(a,"sibling"),start=s(a,"startDate"),end=s(a,"endDate"),restart=s(a,"restartDate");int by=a.getInt(a.getColumnIndexOrThrow("birthYear")),fee=a.getInt(a.getColumnIndexOrThrow("monthlyFee"));a.close();HashMap<Integer,String[]> ps=new HashMap<>();Cursor p=db.payments(id);int total=0;while(p.moveToNext()){int m=p.getInt(p.getColumnIndexOrThrow("month")),amt=p.getInt(p.getColumnIndexOrThrow("amount"));ps.put(m,new String[]{s(p,"marker"),String.valueOf(amt)});total+=amt;}p.close();int W=1080,H=1700;Bitmap bm=Bitmap.createBitmap(W,H,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(bm);c.drawColor(Color.WHITE);Paint q=new Paint(1);q.setTypeface(Typeface.DEFAULT_BOLD);q.setColor(BLACK);q.setTextSize(48);c.drawText("PARION VOLEYBOL AKADEMİSİ",60,80,q);q.setColor(GOLD);q.setTextSize(36);c.drawText("2026 YILI AİDAT BİLANÇOSU",60,135,q);q.setColor(BLACK);q.setTextSize(28);c.drawText("Sporcu: "+name,60,205,q);q.setTypeface(Typeface.DEFAULT);q.setTextSize(24);c.drawText("Doğum Yılı: "+by+"   Grup: "+category+"   Aylık Aidat: "+money(fee),60,245,q);int y=310;for(int m=1;m<=12;m++){String[] x=ps.get(m);String marker=x==null?"":x[0];int amt=x==null?0:Integer.parseInt(x[1]);int color=paymentColor(m,fee,sibling,start,end,restart,marker,amt);q.setColor(color);c.drawRoundRect(45,y-32,1035,y+50,14,14,q);q.setColor(BLACK);q.setTypeface(Typeface.DEFAULT_BOLD);q.setTextSize(25);c.drawText(monthName(m),65,y+7,q);q.setTypeface(Typeface.DEFAULT);q.setTextSize(22);c.drawText(paymentText(m,fee,sibling,start,end,restart,marker,amt),260,y+7,q);y+=92;}q.setColor(BLACK);q.setTypeface(Typeface.DEFAULT_BOLD);q.setTextSize(30);c.drawText("Yıllık Tahsil Edilen: "+money(total),60,y+30,q);q.setTypeface(Typeface.DEFAULT);q.setTextSize(19);c.drawText("Bu belge bilgilendirme amaçlıdır.",60,y+80,q);try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,"Parion_2026_"+name.replace(' ','_')+".png");v.put(MediaStore.Images.Media.MIME_TYPE,"image/png");if(Build.VERSION.SDK_INT>=29)v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Parion");Uri uri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);OutputStream os=getContentResolver().openOutputStream(uri);bm.compress(Bitmap.CompressFormat.PNG,100,os);os.close();Intent sh=new Intent(Intent.ACTION_SEND);sh.setType("image/png");sh.putExtra(Intent.EXTRA_STREAM,uri);sh.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(sh,"Aidat raporunu paylaş"));}catch(Exception e){Toast.makeText(this,"Rapor oluşturulamadı: "+e.getMessage(),Toast.LENGTH_LONG).show();}}

    String s(Cursor c,String col){int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":c.getString(i);}
    String join(String a,String b){if(a.isEmpty())return b;if(b.isEmpty())return a;return a+" • "+b;}
    String money(int x){return String.format(TR,"%,d ₺",x);}
    String monthName(int m){String[] a={"","OCAK","ŞUBAT","MART","NİSAN","MAYIS","HAZİRAN","TEMMUZ","AĞUSTOS","EYLÜL","EKİM","KASIM","ARALIK"};return a[m];}
    int statusColor(String s){if("AKTİF".equals(s))return GREEN;if("ARA VERDİ".equals(s))return ORANGE;return RED;}
    boolean isDate(String x){return x!=null&&x.matches("\\d{4}-\\d{2}-\\d{2}");}
    String dateTr(String x){if(!isDate(x))return x==null?"":x;return x.substring(8,10)+"."+x.substring(5,7)+"."+x.substring(0,4);}
    String toIso(String x){try{return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new SimpleDateFormat("dd.MM.yyyy",TR).parse(x));}catch(Exception e){return x;}}
    int parseInt(String x){try{return Integer.parseInt(x.replace(".","").replace(",","").replace("₺","").trim());}catch(Exception e){return 0;}}
    void goBack(){if("PROFILE".equals(page))showAthletes();else if("LIST".equals(page))showHome();else finish();}
    @Override public void onBackPressed(){if("HOME".equals(page))new AlertDialog.Builder(this).setTitle("ÇIKIŞ?").setMessage("Uygulamadan çıkmak istiyor musunuz?").setPositiveButton("EVET",(d,w)->finish()).setNegativeButton("HAYIR",null).show();else goBack();}
}
