package com.parion.aidat;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.view.*;
import android.widget.*;
import java.text.Collator;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivityV37 extends MainActivityV36 {
    final String[] SORTS={"AD (A-Z)","AD (Z-A)","SOYAD (A-Z)","SOYAD (Z-A)","DOĞUM TARİHİ/YILI ↑","DOĞUM TARİHİ/YILI ↓","GRUP / TAKIM (A-Z)","GRUP / TAKIM (Z-A)","AİDAT ₺ ↑","AİDAT ₺ ↓"};

    @Override public void onCreate(android.os.Bundle b){super.onCreate(b);ensureBirthDateColumn();}
    void ensureBirthDateColumn(){try{Cursor c=db.getReadableDatabase().rawQuery("PRAGMA table_info(athletes)",null);boolean ok=false;while(c.moveToNext())if("birthDate".equals(c.getString(c.getColumnIndexOrThrow("name"))))ok=true;c.close();if(!ok)db.getWritableDatabase().execSQL("ALTER TABLE athletes ADD COLUMN birthDate TEXT");}catch(Exception ignored){}}

    static class AthleteItem {long id;String name,category,status,notes,photo,birthDate;int birthYear,fee;}

    @Override void showAthletes(){
        page="LIST";base("SPORCULAR",true);
        LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(8),dp(8),dp(8),dp(6));panel.setBackground(round(Color.WHITE,10));
        Button add=btn("+ YENİ KAYIT");add.setOnClickListener(v->showAthleteForm(-1));panel.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));
        EditText q=new EditText(this);q.setHint("Sporcu adı ara");panel.addView(q,new LinearLayout.LayoutParams(-1,dp(50)));
        LinearLayout row1=new LinearLayout(this);Spinner st=new Spinner(this),cat=new Spinner(this);String[] sts={"TÜM DURUMLAR","AKTİF","ARA VERDİ","BIRAKTI","ARANACAK","SAKATLANDI"};String[] cats={"TÜM KATEGORİLER","SO 1","SO 2","SO 3","MİNİ VOLEYBOL","MİDİ","KÜÇÜK","YILDIZ","GENÇ"};st.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,sts));cat.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,cats));row1.addView(st,new LinearLayout.LayoutParams(0,dp(50),1));row1.addView(cat,new LinearLayout.LayoutParams(0,dp(50),1));panel.addView(row1);
        LinearLayout row2=new LinearLayout(this);EditText birth=new EditText(this);birth.setHint("Doğum yılı");birth.setInputType(2);Spinner sort=new Spinner(this);sort.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,SORTS));row2.addView(birth,new LinearLayout.LayoutParams(0,dp(50),1));row2.addView(sort,new LinearLayout.LayoutParams(0,dp(50),1));panel.addView(row2);
        Spinner note=new Spinner(this);ArrayList<String> noteItems=new ArrayList<>();noteItems.add("TÜM ÖZEL NOTLAR");noteItems.addAll(db.uniqueNotes());note.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,noteItems));panel.addView(note,new LinearLayout.LayoutParams(-1,dp(54)));root.addView(panel);
        ScrollView sv=scroll();LinearLayout list=box(sv);
        Runnable load=()->loadAthletesSorted(list,q.getText().toString(),String.valueOf(st.getSelectedItem()),String.valueOf(cat.getSelectedItem()),birth.getText().toString(),String.valueOf(note.getSelectedItem()),sort.getSelectedItemPosition());
        android.text.TextWatcher w=new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){load.run();}public void afterTextChanged(android.text.Editable e){}};q.addTextChangedListener(w);birth.addTextChangedListener(w);
        android.widget.AdapterView.OnItemSelectedListener l=new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){load.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}};st.setOnItemSelectedListener(l);cat.setOnItemSelectedListener(l);note.setOnItemSelectedListener(l);sort.setOnItemSelectedListener(l);load.run();
    }

    void loadAthletesSorted(LinearLayout b,String q,String status,String category,String birth,String selectedNote,int sort){
        b.removeAllViews();String sf=(status==null||status.startsWith("TÜM"))?"TÜMÜ":status;Cursor c=db.athletes(q,sf);ArrayList<AthleteItem> xs=new ArrayList<>();int bn=0;try{bn=Integer.parseInt(birth.trim());}catch(Exception ignored){}
        while(c.moveToNext()){AthleteItem a=fromCursor(c);if(category!=null&&!category.startsWith("TÜM")&&!category.equalsIgnoreCase(a.category))continue;if(bn>0&&a.birthYear!=bn)continue;if(selectedNote!=null&&!selectedNote.startsWith("TÜM")&&!selectedNote.trim().equals(a.notes==null?"":a.notes.trim()))continue;xs.add(a);}c.close();Collections.sort(xs,athleteComparator(sort));
        for(AthleteItem a:xs)addAthleteListRow(b,a,null);if(xs.isEmpty()){TextView none=tv("FİLTRELERE UYGUN SPORCU BULUNAMADI",14,Color.DKGRAY,true);none.setGravity(Gravity.CENTER);b.addView(none);}
    }

    AthleteItem fromCursor(Cursor c){AthleteItem a=new AthleteItem();a.id=c.getLong(c.getColumnIndexOrThrow("id"));a.name=s(c,"name");a.category=s(c,"category");a.status=s(c,"status");a.notes=s(c,"notes");a.photo=s(c,"photo");a.birthYear=c.getInt(c.getColumnIndexOrThrow("birthYear"));a.fee=c.getInt(c.getColumnIndexOrThrow("monthlyFee"));int ix=c.getColumnIndex("birthDate");a.birthDate=ix>=0?(c.getString(ix)==null?"":c.getString(ix)):"";return a;}
    Comparator<AthleteItem> athleteComparator(int mode){Collator tr=Collator.getInstance(new Locale("tr","TR"));tr.setStrength(Collator.PRIMARY);return (a,b)->{int r;switch(mode){case 1:r=tr.compare(a.name,b.name);return -r;case 2:return tr.compare(lastName(a.name),lastName(b.name));case 3:r=tr.compare(lastName(a.name),lastName(b.name));return -r;case 4:return birthKey(a).compareTo(birthKey(b));case 5:return b.birthKey(b).compareTo(birthKey(a));case 6:return tr.compare(a.category,b.category);case 7:r=tr.compare(a.category,b.category);return -r;case 8:return Integer.compare(a.fee,b.fee);case 9:return Integer.compare(b.fee,a.fee);default:return tr.compare(a.name,b.name);}};}
    String lastName(String n){if(n==null)return "";String[] p=n.trim().split("\\s+");return p.length==0?"":p[p.length-1];}
    String birthKey(AthleteItem a){if(a.birthDate!=null&&a.birthDate.matches("\\d{4}-\\d{2}-\\d{2}"))return a.birthDate;return String.format(Locale.US,"%04d-01-01",a.birthYear);}

    void addAthleteListRow(LinearLayout b,AthleteItem a,String detail){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(7),dp(8),dp(7));row.setBackground(round(Color.WHITE,10));ImageView av=new ImageView(this);av.setScaleType(ImageView.ScaleType.CENTER_CROP);setAthletePhoto(av,a.photo);row.addView(av,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv((a.birthYear>0?a.birthYear+" • ":"")+a.name,15,BLACK,true));t.addView(tv(a.category+" • "+a.status+" • "+money(a.fee),12,statusColor(a.status),false));if(detail!=null&&!detail.isEmpty())t.addView(tv(detail,12,Color.DKGRAY,false));row.addView(t,new LinearLayout.LayoutParams(0,-2,1));final long id=a.id;row.setOnClickListener(v->showProfile(id));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(7));b.addView(row,lp);}

    @Override void showDashList(String title,LinkedHashMap<Long,DashItem> map){
        page="LIST";base(title,true);Spinner sort=new Spinner(this);sort.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,SORTS));root.addView(sort,new LinearLayout.LayoutParams(-1,dp(54)));ScrollView sv=scroll();LinearLayout b=box(sv);
        Runnable load=()->{b.removeAllViews();ArrayList<DashItem> xs=new ArrayList<>(map.values());Collections.sort(xs,dashComparator(sort.getSelectedItemPosition()));if(xs.isEmpty()){TextView n=tv("Bu grupta sporcu bulunmuyor.",15,Color.DKGRAY,true);n.setGravity(Gravity.CENTER);b.addView(n);return;}for(DashItem d:xs){AthleteItem a=new AthleteItem();a.id=d.id;a.name=d.name;a.category=d.category;a.photo=d.photo;a.birthYear=d.birthYear;a.status="";Cursor c=db.athlete(d.id);if(c.moveToFirst()){a.status=s(c,"status");a.fee=c.getInt(c.getColumnIndexOrThrow("monthlyFee"));int ix=c.getColumnIndex("birthDate");a.birthDate=ix>=0?(c.getString(ix)==null?"":c.getString(ix)):"";}c.close();LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(8),dp(8),dp(8));row.setBackground(round(Color.WHITE,10));ImageView av=new ImageView(this);av.setScaleType(ImageView.ScaleType.CENTER_CROP);setAthletePhoto(av,a.photo);row.addView(av,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);t.addView(tv((a.birthYear>0?a.birthYear+" • ":"")+a.name,15,BLACK,true));t.addView(tv(a.category+" • "+money(a.fee),12,Color.DKGRAY,false));t.addView(tv(d.detail,12,Color.DKGRAY,false));row.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView amt=tv(money(d.amount),14,BLACK,true);amt.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);row.addView(amt,new LinearLayout.LayoutParams(dp(115),-1));final long id=a.id;row.setOnClickListener(v->showProfile(id));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(7));b.addView(row,lp);}};
        sort.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){load.run();}public void onNothingSelected(android.widget.AdapterView<?> p){}});load.run();
    }
    Comparator<DashItem> dashComparator(int mode){return (x,y)->{AthleteItem a=new AthleteItem(),b=new AthleteItem();a.id=x.id;a.name=x.name;a.category=x.category;a.birthYear=x.birthYear;b.id=y.id;b.name=y.name;b.category=y.category;b.birthYear=y.birthYear;fillFeeBirth(a);fillFeeBirth(b);return athleteComparator(mode).compare(a,b);};}
    void fillFeeBirth(AthleteItem a){Cursor c=db.athlete(a.id);if(c.moveToFirst()){a.fee=c.getInt(c.getColumnIndexOrThrow("monthlyFee"));a.status=s(c,"status");int ix=c.getColumnIndex("birthDate");a.birthDate=ix>=0?(c.getString(ix)==null?"":c.getString(ix)):"";}c.close();}

    @Override void showProfile(long id){super.showProfile(id);LinearLayout b=findContentBox(root);if(b==null)return;LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);Button edit=btn("BİLGİLERİ DÜZENLE"),del=btn("SPORCUYU SİL");edit.setOnClickListener(v->showAthleteForm(id));del.setBackground(round(Color.rgb(245,210,210),12));del.setOnClickListener(v->confirmDelete(id));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(56),1);p.setMargins(dp(2),dp(8),dp(2),dp(4));r.addView(edit,p);r.addView(del,p);b.addView(r);}
    LinearLayout findContentBox(View v){if(v instanceof ScrollView){ScrollView s=(ScrollView)v;if(s.getChildCount()>0&&s.getChildAt(0) instanceof LinearLayout)return (LinearLayout)s.getChildAt(0);}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){LinearLayout x=findContentBox(g.getChildAt(i));if(x!=null)return x;}}return null;}

    void showAthleteForm(long id){
        page="FORM";base(id<0?"YENİ SPORCU KAYDI":"SPORCU BİLGİLERİNİ DÜZENLE",true);ScrollView sv=scroll();LinearLayout b=box(sv);Cursor c=id>=0?db.athlete(id):null;if(c!=null)c.moveToFirst();
        EditText name=field("AD SOYAD",val(c,"name"));EditText bd=field("DOĞUM TARİHİ (gg.aa.yyyy)",birthDisplay(c));EditText cat=field("GRUP / TAKIM",val(c,"category"));Spinner status=spinner(new String[]{"AKTİF","ARA VERDİ","BIRAKTI","ARANACAK","SAKATLANDI"},val(c,"status"));EditText fee=field("AYLIK AİDAT ₺",num(c,"monthlyFee"));fee.setInputType(2);Spinner sibling=spinner(new String[]{"TEK","VAR","BURSLU"},val(c,"sibling"));EditText phone=field("SPORCU TELEFON",val(c,"phone"));EditText mn=field("ANNE ADI",val(c,"motherName"));EditText mp=field("ANNE TELEFON",val(c,"motherPhone"));EditText fn=field("BABA ADI",val(c,"fatherName"));EditText fp=field("BABA TELEFON",val(c,"fatherPhone"));EditText start=field("BAŞLANGIÇ TARİHİ (gg.aa.yyyy)",dateInput(c,"startDate"));EditText end=field("BİTİŞ / ARA VERME TARİHİ",dateInput(c,"endDate"));EditText restart=field("YENİDEN BAŞLAMA TARİHİ",dateInput(c,"restartDate"));EditText notes=field("ÖZEL NOTLAR",val(c,"notes"));notes.setMinLines(3);if(c!=null)c.close();
        b.addView(name);b.addView(bd);b.addView(cat);b.addView(label("DURUM"));b.addView(status);b.addView(fee);b.addView(label("KARDEŞ / BURSLU"));b.addView(sibling);b.addView(phone);b.addView(mn);b.addView(mp);b.addView(fn);b.addView(fp);b.addView(start);b.addView(end);b.addView(restart);b.addView(notes);
        Button save=btn(id<0?"KAYDI OLUŞTUR":"DEĞİŞİKLİKLERİ KAYDET");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(60));sp.setMargins(0,dp(14),0,dp(10));b.addView(save,sp);save.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){Toast.makeText(this,"Ad Soyad zorunludur.",Toast.LENGTH_SHORT).show();return;}ContentValues cv=new ContentValues();cv.put("name",name.getText().toString().trim().toUpperCase(new Locale("tr","TR")));String birthIso=toIsoOrEmpty(bd.getText().toString());cv.put("birthDate",birthIso);cv.put("birthYear",birthIso.length()>=4?parseInt(birthIso.substring(0,4)):0);cv.put("category",cat.getText().toString().trim().toUpperCase(new Locale("tr","TR")));cv.put("status",String.valueOf(status.getSelectedItem()));cv.put("monthlyFee",parseInt(fee.getText().toString()));cv.put("sibling",String.valueOf(sibling.getSelectedItem()));cv.put("phone",phone.getText().toString().trim());cv.put("motherName",mn.getText().toString().trim().toUpperCase(new Locale("tr","TR")));cv.put("motherPhone",mp.getText().toString().trim());cv.put("fatherName",fn.getText().toString().trim().toUpperCase(new Locale("tr","TR")));cv.put("fatherPhone",fp.getText().toString().trim());cv.put("startDate",toIsoOrEmpty(start.getText().toString()));cv.put("endDate",toIsoOrEmpty(end.getText().toString()));cv.put("restartDate",toIsoOrEmpty(restart.getText().toString()));cv.put("notes",notes.getText().toString().trim());SQLiteDatabase d=db.getWritableDatabase();long saved=id;if(id<0){Cursor mx=d.rawQuery("SELECT COALESCE(MAX(seq),0)+1 FROM athletes",null);mx.moveToFirst();cv.put("seq",mx.getInt(0));mx.close();cv.put("photo","");saved=d.insert("athletes",null,cv);}else d.update("athletes",cv,"id=?",new String[]{String.valueOf(id)});if(saved>0){Toast.makeText(this,id<0?"Yeni sporcu kaydedildi.":"Bilgiler güncellendi.",Toast.LENGTH_SHORT).show();showProfile(saved);}else Toast.makeText(this,"Kayıt işlemi başarısız.",Toast.LENGTH_LONG).show();});
    }

    EditText field(String hint,String value){EditText e=new EditText(this);e.setHint(hint);e.setText(value==null?"":value);e.setTextSize(14);e.setPadding(dp(10),dp(7),dp(10),dp(7));return e;}
    TextView label(String x){return tv(x,12,Color.DKGRAY,true);}
    Spinner spinner(String[] opts,String selected){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,opts));for(int i=0;i<opts.length;i++)if(opts[i].equalsIgnoreCase(selected)){s.setSelection(i);break;}return s;}
    String val(Cursor c,String col){if(c==null)return "";int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":c.getString(i);}
    String num(Cursor c,String col){if(c==null)return "";int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":String.valueOf(c.getInt(i));}
    String birthDisplay(Cursor c){if(c==null)return "";String x=val(c,"birthDate");if(!x.isEmpty())return dateTr(x);int y=0;int i=c.getColumnIndex("birthYear");if(i>=0)y=c.getInt(i);return y>0?"01.01."+y:"";}
    String dateInput(Cursor c,String col){String x=val(c,col);return x.isEmpty()?"":dateTr(x);}
    String toIsoOrEmpty(String x){x=x==null?"":x.trim();if(x.isEmpty()||"—".equals(x))return "";String iso=toIso(x);return iso==null?"":iso;}

    void confirmDelete(long id){Cursor c=db.athlete(id);String name="SPORCU";if(c.moveToFirst())name=s(c,"name");c.close();final String n=name;new AlertDialog.Builder(this).setTitle("SPORCUYU SİL").setMessage(n+" adlı sporcuyu ve aidat geçmişini kalıcı olarak silmek istediğinize emin misiniz?").setPositiveButton("SİL",(d,w)->new AlertDialog.Builder(this).setTitle("SON ONAY").setMessage("Bu işlem geri alınamaz.").setPositiveButton("EVET, SİL",(a,z)->deleteAthlete(id)).setNegativeButton("VAZGEÇ",null).show()).setNegativeButton("İPTAL",null).show();}
    void deleteAthlete(long id){SQLiteDatabase d=db.getWritableDatabase();d.beginTransaction();try{d.delete("payments","athleteId=?",new String[]{String.valueOf(id)});d.delete("fee_history","athleteId=?",new String[]{String.valueOf(id)});d.delete("athletes","id=?",new String[]{String.valueOf(id)});d.setTransactionSuccessful();}finally{d.endTransaction();}Toast.makeText(this,"Sporcu kaydı silindi.",Toast.LENGTH_SHORT).show();showAthletes();}
}
