package com.parion.aidat;

import android.app.*;import android.os.Bundle;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.text.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 DbHelper db;LinearLayout root,content;int year,month;long photoTarget=-1;ImageView photoPreview;Uri pickedPhoto;final int GOLD=Color.rgb(242,201,76),BLACK=Color.rgb(17,17,17),BG=Color.rgb(247,247,247),RED=Color.rgb(190,35,35),YELLOW=Color.rgb(245,190,20);NumberFormat money=NumberFormat.getCurrencyInstance(new Locale("tr","TR"));String[] months={"Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"};String[] payMethods={"Nakit Yavuz","Nakit Gonca","Nakit 3. Antrenör","Nakit 4. Antrenör","EFT Yavuz","EFT Gonca"};
 @Override public void onCreate(Bundle b){super.onCreate(b);db=new DbHelper(this);Calendar c=Calendar.getInstance();year=c.get(Calendar.YEAR);month=c.get(Calendar.MONTH)+1;shell();dashboard();}
 int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int sp,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(BLACK);t.setPadding(dp(10),dp(8),dp(10),dp(8));if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;} EditText field(String h,int type){EditText e=new EditText(this);e.setHint(h);e.setInputType(type);e.setPadding(dp(8),dp(7),dp(8),dp(7));return e;} void clear(){content.removeAllViews();}
 void shell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setBackgroundColor(BLACK);TextView logo=tv("P",28,true);logo.setGravity(Gravity.CENTER);logo.setTextColor(BLACK);logo.setBackgroundColor(GOLD);head.addView(logo,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView title=tv("PARION\nSPOR KULÜBÜ",19,true);title.setTextColor(GOLD);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));root.addView(head,new LinearLayout.LayoutParams(-1,dp(72)));ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(10),dp(12),dp(90));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));HorizontalScrollView hsv=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(BLACK);String[] labs={"Ana Sayfa","Sporcu Ara","+ Sporcu","Aidatlar","Yoklama","Stok","Aidat Güncelle"};for(String s:labs){Button b=btn(s);b.setTextColor(s.equals("+ Sporcu")?BLACK:GOLD);if(s.equals("+ Sporcu"))b.setBackgroundColor(GOLD);b.setOnClickListener(v->{if(s.equals("Ana Sayfa"))dashboard();else if(s.equals("Sporcu Ara"))searchScreen();else if(s.equals("+ Sporcu"))athleteForm();else if(s.equals("Aidatlar"))feeScreen();else if(s.equals("Yoklama"))attendanceGroups();else if(s.equals("Stok"))inventoryScreen();else bulkFeeScreen();});nav.addView(b,new LinearLayout.LayoutParams(dp(118),dp(62)));}hsv.addView(nav);root.addView(hsv);setContentView(root);}
 void heading(String s){content.addView(tv(s,23,true));} void card(String a,String b){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundColor(Color.WHITE);c.addView(tv(a,13,false));c.addView(tv(b,23,true));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(4),0,dp(4));content.addView(c,p);}
 void monthNav(Runnable refresh){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER);Button p=btn("‹"),n=btn("›");TextView t=tv(months[month-1]+" "+year,19,true);t.setGravity(Gravity.CENTER);p.setOnClickListener(v->{month--;if(month==0){month=12;year--;}refresh.run();});n.setOnClickListener(v->{month++;if(month==13){month=1;year++;}refresh.run();});r.addView(p,new LinearLayout.LayoutParams(dp(55),-2));r.addView(t,new LinearLayout.LayoutParams(0,-2,1));r.addView(n,new LinearLayout.LayoutParams(dp(55),-2));content.addView(r);}
 void dashboard(){clear();heading("Ana Sayfa");monthNav(()->dashboard());double e=db.expectedTotal(year,month),c=db.collected(year,month);card("Beklenen aidat",money.format(e));card("Tahsil edilen",money.format(c));card("Kalan",money.format(Math.max(0,e-c)));card("Ödeme beklenen",db.unpaidCount(year,month)+" sporcu");Button s=btn("🔎 Sporcu Ara");s.setOnClickListener(v->searchScreen());content.addView(s);Button a=btn("✓ Yoklama");a.setOnClickListener(v->attendanceGroups());content.addView(a);Button st=btn("Stok Takip");st.setOnClickListener(v->inventoryScreen());content.addView(st);Cursor ab=db.absentOver10Days();if(ab.moveToFirst()){content.addView(tv("10+ GÜN DEVAMSIZLAR",17,true));do{content.addView(tv("• "+ab.getString(ab.getColumnIndexOrThrow("name")),15,false));}while(ab.moveToNext());}ab.close();content.addView(tv("Parion Aidat Takip • v2.0 Pilot • Yerel veri",12,false));}

 void searchScreen(){clear();heading("Sporcu Ara");EditText q=field("Ad soyad veya TCKN",InputType.TYPE_CLASS_TEXT);Button b=btn("Ara");content.addView(q);content.addView(b);LinearLayout results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);content.addView(results);b.setOnClickListener(v->{results.removeAllViews();Cursor c=db.searchAthletes(q.getText().toString().trim());while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));Button x=btn(c.getString(c.getColumnIndexOrThrow("name"))+"  •  "+c.getString(c.getColumnIndexOrThrow("groupName")));x.setOnClickListener(z->athleteDetail(id));results.addView(x);}c.close();});}
 String val(Cursor c,String col){int i=c.getColumnIndex(col);return i<0||c.isNull(i)?"":c.getString(i);}int ival(Cursor c,String col){int i=c.getColumnIndex(col);return i<0||c.isNull(i)?0:c.getInt(i);}
 void athleteDetail(long id){clear();Cursor c=db.athlete(id);if(!c.moveToFirst()){c.close();return;}heading(val(c,"name"));String uri=val(c,"photoUri");ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.CENTER_CROP);if(!uri.isEmpty())try{im.setImageURI(Uri.parse(uri));}catch(Exception ignored){}content.addView(im,new LinearLayout.LayoutParams(-1,dp(210)));String[][] rows={{"Durum",ival(c,"active")==1?"Aktif":"Bıraktı"},{"Doğum",val(c,"birthDate")},{"TCKN",val(c,"tckn")},{"Başlangıç",val(c,"startDate")},{"Sporcu Tel",val(c,"athletePhone")},{"Anne",val(c,"motherName")+"  "+val(c,"motherPhone")},{"Baba",val(c,"fatherName")+"  "+val(c,"fatherPhone")},{"Okul",val(c,"school")+"  "+val(c,"classBranch")},{"Grup",val(c,"groupName")},{"Aidat",ival(c,"scholarship")==1?"BURSLU":money.format(c.getDouble(c.getColumnIndexOrThrow("monthlyFee")))},{"Rahatsızlık",val(c,"illnesses")},{"Not",val(c,"notes")},{"Bırakma",val(c,"leaveDate")+"  "+val(c,"leaveReason")},{"Ekipman","Tişört: "+ival(c,"tshirtQty")+" • Forma: "+ival(c,"jerseyQty")+" • Eşofman: "+ival(c,"tracksuitQty")}};for(String[] r:rows)content.addView(tv(r[0]+":  "+r[1],14,r[0].equals("Aidat")));c.close();Button f=btn("Aidat / burs durumunu güncelle");f.setOnClickListener(v->singleFeeDialog(id));content.addView(f);Button eq=btn("Ekipman adetlerini güncelle");eq.setOnClickListener(v->equipmentDialog(id));content.addView(eq);content.addView(tv("ÖDEME GEÇMİŞİ",17,true));Cursor p=db.paymentsFor(id);while(p.moveToNext())content.addView(tv(months[p.getInt(p.getColumnIndexOrThrow("month"))-1]+" "+p.getInt(p.getColumnIndexOrThrow("year"))+" • "+money.format(p.getDouble(p.getColumnIndexOrThrow("amount")))+" • "+val(p,"method"),14,false));p.close();}
 void singleFeeDialog(long id){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText fee=field("Yeni aidat ₺",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL),date=field("Geçerlilik tarihi (yyyy-aa-gg)",InputType.TYPE_CLASS_DATETIME);date.setText(new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));CheckBox burs=new CheckBox(this);burs.setText("Burslu");f.addView(fee);f.addView(date);f.addView(burs);new AlertDialog.Builder(this).setTitle("Aidat Güncelle").setView(f).setNegativeButton("Vazgeç",null).setPositiveButton("Kaydet",(d,w)->{db.updateFee(id,num(fee.getText().toString(),0),burs.isChecked(),date.getText().toString());athleteDetail(id);}).show();}
 void equipmentDialog(long id){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText t=field("Tişört adedi",2),j=field("Forma adedi",2),e=field("Eşofman adedi",2);f.addView(t);f.addView(j);f.addView(e);new AlertDialog.Builder(this).setTitle("Ekipman").setView(f).setNegativeButton("Vazgeç",null).setPositiveButton("Kaydet",(d,w)->{db.updateEquipment(id,intv(t),intv(j),intv(e));athleteDetail(id);}).show();}

 void athleteForm(){clear();heading("Yeni Sporcu Kaydı");ImageView im=new ImageView(this);im.setImageResource(android.R.drawable.ic_menu_camera);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);content.addView(im,new LinearLayout.LayoutParams(-1,dp(150)));photoPreview=im;Button ph=btn("Telefondan Sporcu Fotoğrafı Seç");ph.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,55);});content.addView(ph);EditText name=addF("Sporcu adı soyadı",1),birth=addF("Doğum tarihi (g/a/y)",1),tckn=addF("TCKN (11 hane)",2),start=addF("Başlangıç tarihi (g/a/y)",1),atel=addF("Sporcu telefonu",3),mother=addF("Anne adı",1),mtel=addF("Anne telefon",3),father=addF("Baba adı",1),ftel=addF("Baba telefon",3),school=addF("Okulu",1),cl=addF("Sınıf / şube",1);Spinner group=new Spinner(this);ArrayList<String> gl=groupNames(false);group.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,gl));content.addView(label("Grup"));content.addView(group);EditText fee=addF("Aylık aidat ₺",2);Spinner status=new Spinner(this);status.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Ücretli","Burslu"}));content.addView(label("Aidat durumu"));content.addView(status);status.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long x){if(pos==1){fee.setText("0");fee.setEnabled(false);}else fee.setEnabled(true);}});EditText ill=addF("Geçirdiği rahatsızlıklar",1),notes=addF("Özel notlar",1),leave=addF("Bırakma tarihi (g/a/y) - varsa",1),reason=addF("Bırakma nedeni",1),tshirt=addF("Tişört adedi",2),jersey=addF("Forma adedi",2),tracksuit=addF("Eşofman adedi",2);Button save=btn("SPORCUYU KAYDET");save.setBackgroundColor(GOLD);save.setOnClickListener(v->{String tc=tckn.getText().toString().trim();if(name.getText().toString().trim().isEmpty()){toast("Sporcu adı gerekli");return;}if(!tc.isEmpty()&&tc.length()!=11){toast("TCKN 11 hane olmalı");return;}String st=toIso(start.getText().toString()),bd=toIso(birth.getText().toString()),ld=toIso(leave.getText().toString());db.addAthlete(name.getText().toString().trim(),bd,tc,st,atel.getText().toString(),mother.getText().toString(),mtel.getText().toString(),father.getText().toString(),ftel.getText().toString(),school.getText().toString(),cl.getText().toString(),gl.isEmpty()?"":gl.get(group.getSelectedItemPosition()),num(fee.getText().toString(),0),status.getSelectedItemPosition()==1,ill.getText().toString(),notes.getText().toString(),ld,reason.getText().toString(),pickedPhoto==null?"":pickedPhoto.toString(),intv(tshirt),intv(jersey),intv(tracksuit));pickedPhoto=null;toast("Sporcu kaydedildi");dashboard();});content.addView(save);}
 EditText addF(String h,int type){int it=type==2?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL:type==3?InputType.TYPE_CLASS_PHONE:InputType.TYPE_CLASS_TEXT;EditText e=field(h,it);content.addView(e);return e;}TextView label(String s){TextView t=tv(s,13,true);t.setPadding(dp(8),dp(12),dp(8),0);return t;}
 @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==55&&c==RESULT_OK&&data!=null){pickedPhoto=data.getData();try{getContentResolver().takePersistableUriPermission(pickedPhoto,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}if(photoPreview!=null)photoPreview.setImageURI(pickedPhoto);}}

 void feeScreen(){clear();heading("Aidat Takip");monthNav(()->feeScreen());Spinner filter=new Spinner(this);filter.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"1 Ay","3 Ay","6 Ay","1 Yıl","Tümü"}));content.addView(label("Görünüm filtresi"));content.addView(filter);Cursor c=db.activeAthletes();while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));String name=val(c,"name");double due=db.expectedForMonth(id,year,month);boolean paid=db.isPaid(id,year,month);Button b=btn(name+" • "+(due==0?"Aidat yok":money.format(due))+" • "+(paid?"ÖDENDİ":"BEKLİYOR"));b.setTextColor(feeColor(id,year,month,paid,due));b.setOnClickListener(v->{if(due<=0){athleteDetail(id);return;}if(paid){new AlertDialog.Builder(this).setMessage("Ödeme kaydı geri alınsın mı?").setPositiveButton("Evet",(d,w)->{db.removePayment(id,year,month);feeScreen();}).setNegativeButton("Hayır",null).show();}else paymentDialog(id,name,due);});content.addView(b);}c.close();}
 int feeColor(long id,int y,int m,boolean paid,double due){if(paid)return Color.rgb(25,130,60);Calendar now=Calendar.getInstance(),target=Calendar.getInstance();target.clear();target.set(y,m-1,1);Calendar max=(Calendar)now.clone();max.add(Calendar.DAY_OF_YEAR,62);if(target.after(max)||due<=0)return BLACK;String dd=db.dueDate(id,y,m);try{Date d=new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(dd);return d.before(new Date())?RED:YELLOW;}catch(Exception e){return YELLOW;}}
 void paymentDialog(long id,String name,double due){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText amount=field("Tutar",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);amount.setText(String.valueOf((int)due));Spinner method=new Spinner(this);method.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,payMethods));f.addView(tv(name+" • "+months[month-1]+" "+year,14,true));f.addView(amount);f.addView(method);new AlertDialog.Builder(this).setTitle("Ödeme Kaydı").setView(f).setNegativeButton("Vazgeç",null).setPositiveButton("Kaydet",(d,w)->{Calendar now=Calendar.getInstance(),t=Calendar.getInstance();t.clear();t.set(year,month-1,1);Calendar mx=(Calendar)now.clone();mx.add(Calendar.DAY_OF_YEAR,62);if(t.after(mx)){toast("62 günden daha ileri aya ödeme girilemez");return;}db.markPaid(id,year,month,num(amount.getText().toString(),due),payMethods[method.getSelectedItemPosition()]);feeScreen();}).show();}

 void bulkFeeScreen(){clear();heading("Aidat Güncelleme");ArrayList<String> gs=groupNames(false);Spinner g=new Spinner(this);g.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,gs));EditText old=addStandalone("Mevcut aidat (örn. 3000)",2),nw=addStandalone("Yeni aidat",2),date=addStandalone("Geçerlilik tarihi (g/a/y)",1);content.addView(label("Grup"),0);content.addView(g,1);Button go=btn("Eşleşen Sporcuları Toplu Güncelle");go.setOnClickListener(v->{if(gs.isEmpty())return;int n=db.bulkUpdateFee(gs.get(g.getSelectedItemPosition()),num(old.getText().toString(),0),num(nw.getText().toString(),0),toIso(date.getText().toString()));toast(n+" sporcu güncellendi. Özel ücretlileri Sporcu Ara'dan tek tek güncelleyebilirsin.");});content.addView(go);content.addView(tv("Bu işlem yalnızca seçilen grupta mevcut aidatı yazdığın tutarla eşleşen ücretli sporcuları değiştirir. Eski dönem aidatları eski ücret tarihçesiyle korunur.",13,false));}
 EditText addStandalone(String h,int type){return field(h,type==2?InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL:InputType.TYPE_CLASS_TEXT);}

 ArrayList<String> groupNames(boolean sports){ArrayList<String>a=new ArrayList<>();Cursor c=db.groups(sports);while(c.moveToNext())a.add(c.getString(c.getColumnIndexOrThrow("name")));c.close();return a;}
 void attendanceGroups(){clear();heading("Yoklama • Spor Okulu");ArrayList<String> gs=groupNames(true);for(String g:gs){Button b=btn(g);b.setOnClickListener(v->attendanceMonth(g));content.addView(b);}Button add=btn("+ Grup / takım tanımla");add.setOnClickListener(v->groupDialog());content.addView(add);}
 void groupDialog(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText n=field("Grup adı",1);CheckBox s=new CheckBox(this);s.setText("Spor okulu grubu (yoklama oluştur)");s.setChecked(true);f.addView(n);f.addView(s);new AlertDialog.Builder(this).setTitle("Grup Tanımla").setView(f).setPositiveButton("Kaydet",(d,w)->{db.addGroup(n.getText().toString().trim(),s.isChecked());attendanceGroups();}).setNegativeButton("Vazgeç",null).show();}
 void attendanceMonth(String group){clear();heading(group+" Yoklama");monthNav(()->attendanceMonth(group));int[] sch=db.scheduleDays(group);if(sch.length==0){content.addView(tv("Bu grup için antrenman günleri seçilmemiş.",14,false));Button set=btn("Haftalık Antrenman Günlerini Seç");set.setOnClickListener(v->scheduleDialog(group));content.addView(set);return;}Button change=btn("Program değişti • Yeni günleri seç");change.setOnClickListener(v->scheduleDialog(group));content.addView(change);ArrayList<String> dates=db.trainingDates(group,year,month);for(String date:dates){Button b=btn(date+" yoklamasını aç");b.setOnClickListener(v->attendanceDate(group,date));content.addView(b);}}
 void scheduleDialog(String group){String[] ds={"Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar"};boolean[] sel=new boolean[7];new AlertDialog.Builder(this).setTitle(group+" • Antrenman Günleri").setMultiChoiceItems(ds,sel,(d,w,c)->sel[w]=c).setPositiveButton("Kaydet",(d,w)->{db.setSchedule(group,sel);attendanceMonth(group);}).setNegativeButton("Vazgeç",null).show();}
 void attendanceDate(String group,String date){clear();heading(group+" • "+date);Cursor c=db.athletesByGroup(group);ArrayList<Long> ids=new ArrayList<>();ArrayList<CheckBox> checks=new ArrayList<>();while(c.moveToNext()){long id=c.getLong(c.getColumnIndexOrThrow("id"));ids.add(id);CheckBox cb=new CheckBox(this);cb.setText(val(c,"name"));cb.setChecked(db.attendanceValue(id,date));checks.add(cb);content.addView(cb);}c.close();Button save=btn("YOKLAMAYI KAYDET");save.setBackgroundColor(GOLD);save.setOnClickListener(v->{for(int i=0;i<ids.size();i++)db.saveAttendance(ids.get(i),group,date,checks.get(i).isChecked());toast("Yoklama kaydedildi");dashboard();});content.addView(save);}

 void inventoryScreen(){clear();heading("Stok Takip");Calendar c=Calendar.getInstance();String from=String.format(Locale.US,"%04d-%02d-01",c.get(Calendar.YEAR),c.get(Calendar.MONTH)+1),to=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());card("Bu ay ekipman kârı",money.format(db.inventoryProfit(from,to)));Cursor x=db.inventory();while(x.moveToNext()){long id=x.getLong(x.getColumnIndexOrThrow("id"));String name=val(x,"name");int stock=x.getInt(x.getColumnIndexOrThrow("stock"));double buy=x.getDouble(x.getColumnIndexOrThrow("buyPrice")),sell=x.getDouble(x.getColumnIndexOrThrow("sellPrice"));Button b=btn(name+" • Stok: "+stock+" • Alış "+money.format(buy)+" • Satış "+money.format(sell));b.setOnClickListener(v->inventoryTxDialog(id,name,buy,sell));content.addView(b);}x.close();Button add=btn("+ Diğer ekipman ekle");add.setOnClickListener(v->inventoryAddDialog());content.addView(add);}
 void inventoryTxDialog(long id,String name,double buy,double sell){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Stok Girişi","Satış"}));EditText q=field("Adet",2),bp=field("Birim alış fiyatı",2),sp=field("Birim satış fiyatı",2);bp.setText(String.valueOf(buy));sp.setText(String.valueOf(sell));f.addView(type);f.addView(q);f.addView(bp);f.addView(sp);new AlertDialog.Builder(this).setTitle(name).setView(f).setPositiveButton("Kaydet",(d,w)->{db.inventoryTx(id,intv(q),type.getSelectedItemPosition()==0?"IN":"OUT",num(bp.getText().toString(),buy),num(sp.getText().toString(),sell),null);inventoryScreen();}).setNegativeButton("Vazgeç",null).show();}
 void inventoryAddDialog(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);EditText n=field("Ekipman adı",1),q=field("Başlangıç stok",2),b=field("Alış fiyatı",2),s=field("Satış fiyatı",2);f.addView(n);f.addView(q);f.addView(b);f.addView(s);new AlertDialog.Builder(this).setTitle("Ekipman Ekle").setView(f).setPositiveButton("Kaydet",(d,w)->{db.addInventoryItem(n.getText().toString(),intv(q),num(b.getText().toString(),0),num(s.getText().toString(),0));inventoryScreen();}).setNegativeButton("Vazgeç",null).show();}

 int intv(EditText e){try{return Integer.parseInt(e.getText().toString());}catch(Exception x){return 0;}}double num(String s,double d){try{return Double.parseDouble(s.replace(',','.'));}catch(Exception e){return d;}}String toIso(String s){s=s.trim();if(s.isEmpty())return "";String[] p=s.split("[/.-]");if(p.length==3)try{int d=Integer.parseInt(p[0]),m=Integer.parseInt(p[1]),y=Integer.parseInt(p[2]);if(y<100)y+=2000;return String.format(Locale.US,"%04d-%02d-%02d",y,m,d);}catch(Exception ignored){}if(s.matches("\\d{4}-\\d{2}-\\d{2}"))return s;return s;}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
